### ISSUE TITLE
Have you tried to build the project in qt6.2?

### ISSUE THREAD

**Issue by comiquita** [AmonRaNet/QGeoView#12]
I'm trying to build the project in qt6.2 but I'm getting tons of errors.

e.g. ../../QGeoView/lib/src/QGVMapQGView.cpp:242:40: error: no member named 'pos' in 'QWheelEvent'
        mWheelMouseArea = QRect(event->pos(), QSize(1, 1))

../../QGeoView/lib/src/QGVMapQGView.cpp:256:16: error: no member named 'delta' in 'QWheelEvent'
    if (event->delta() > 0) {

**Comment by embeddedmz** [comment]
Because the API changed between Qt5 and Qt6 : https://doc-snapshots.qt.io/qt6-dev/qwheelevent.html https://doc.qt.io/qt-5/qwheelevent.html

Stick to Qt5

**Comment by comiquita** [comment]
Yes, you're correct. 

The problem is I need to use qt6.2 since I have a requirement to develop a project (related to slippy maps) in qt6.2.

**Comment by AmonRaNet** [comment]
If it is only problem - it could be easy to fix :)

**Comment by AmonRaNet** [comment]
> Hey Comiquita, I've been using qgeoview for a while in qt 6.x. I recall there were like 4 files that required changes which should be attached. It's not immediately clear to me how CMake could toggle between qt5 and qt6 automagically. Cheers
> 
> [filesToUpdate.gz](https://github.com/AmonRaNet/QGeoView/files/7825174/filesToUpdate.gz)

@comiquita I have fast checked your code - looks promising for me - you can open PR with your changes. cmake cant toggle automagically between Qt5 or Qt6 from cmake file itself, because it is environment variable (path to package). It is same story for qmake

**Comment by AmonRaNet** [comment]
Master is updated and Qt6 now should be supported. Thanks to @bakerb845!
