### ISSUE TITLE
Application exits when minimized under Windows 10

### ISSUE THREAD

**Issue by embeddedmz** [AmonRaNet/QGeoView#13]
Hi Andrey,

I built 2 versions of QGeoView using VS2019 + CMake + vcpkg and the second one using Qt Creator + QMake when I minimize the window the application shuts down ??!!??

I posted a question on SO : https://stackoverflow.com/questions/69195122/qt-application-exits-with-0-when-qmainwindow-is-minimized

Regards.

**Comment by embeddedmz** [comment]
OK, someone gave a response on StackOverflow, can I remove hideEvent from MainWindow class and send you a pull request ?

**Comment by AmonRaNet** [comment]
yes - sure
