### ISSUE TITLE
[Security] Workflow pre-commit.yaml is using vulnerable action pre-commit/action

### ISSUE THREAD

**Issue by fockboi-lgtm** [AmonRaNet/QGeoView#15]
The workflow pre-commit.yaml is referencing action pre-commit/action using references v2.0.0. However this reference is missing the commit [80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7](https://github.com/pre-commit/action/commits/80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by AmonRaNet** [comment]
@fockboi-lgtm I have updated all action files to use latest version: https://github.com/AmonRaNet/QGeoView/pull/16
With pre-commit latest is 2.0.3 which not includes 80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7. When I trying to use this commit or simply master then action is failed. Some error about some missing file. You know how to fix it?
