### ISSUE TITLE
Movable and Transformed QGVDrawItem

### ISSUE THREAD

**Issue by JaiPasdeBol** [AmonRaNet/QGeoView#20]
Hello,

Just to warn you that in case we do a rectangle which is both Movable and Transformed we need to add "refresh" inside the "projOnObjectMovePos" function otherwise the movement may be strange.

```
void Rectangle::projOnObjectMovePos(const QPointF& projPos)
{
    mProjRect.moveCenter(projPos);
    mGeoRect = getMap()->getProjection()->projToGeo(mProjRect);
    resetBoundary();
    refresh();
    qInfo() << "object moved" << mGeoRect;
} 
```
I think it's correct, but maybe would you find a more efficient way to correct it...

JPB

**Comment by AmonRaNet** [comment]
You are right - fixed.
Actually only refresh() is enough.
Nice catch!
