### ISSUE TITLE
Add Cache for Online Tile

### ISSUE THREAD

**Issue by muby** [AmonRaNet/QGeoView#25]
First of all ! Nice work !

I can suggest you to add a cache : 

- Memory cache 
- HDD Cache
- Sqlite Cache

It could be nice to be able when you have already downloaded some tile, to be able to access it offline.

**Comment by AmonRaNet** [comment]
Thanks!
Depends what you understand under cache.
- run-time cache, which are used to avoid download for tiles which was already requested. This is managed by QNetworkDiskCache for QNetworkAccessManager.
```
    mCache = new QNetworkDiskCache(this);
    mCache->setCacheDirectory("cacheDir");
    mManager = new QNetworkAccessManager(this);
    mManager->setCache(mCache);
    QGV::setNetworkManager(mManager);

```
You can create own instance of QAbstractNetworkCache and store data as you want it.

- offline tiles, which are used to make system fully offline. Here is no direct solution. 

If you want to do it without changes in QGeoView: for example you can define custom "offline" url scheme and create custom QNetworkAccessManager, which will use custom scheme as sign for "offline" files. Then you can define as layer QGVLayerOSM with QGVLayerOSM::setUrl("offline://${z}/${x}/${y}.png")

Other way is create new `class QGVLayerTilesOffline : public QGVLayerTiles` (please look to QGVLayerTilesOnline) and override QGVLayerTiles::request. Then you can load image for tile from any source and call after QGVLayerTiles::onTile with image item.

P.S.
In any case you need somehow create offline cache of tiles - and this is completely other topic. QGeoView will not help much with this. Please, be careful about legacy aspects and copyright. Especially about Google, Bing.
