### ISSUE TITLE
How to draw a curve line, the red dot moving on the red curve

### ISSUE THREAD

**Issue by wangdemon** [AmonRaNet/QGeoView#27]
As shown in the figure below
![微信截图_20220329153611](https://user-images.githubusercontent.com/20681339/160558725-d06cae5c-fbf4-4cfd-971a-bdf872dc35ff.png)

**Comment by embeddedmz** [comment]
There's some web sites that can help you to draw stuff on a map and get the list of geo coords related to what you have drew (JSON, CSV). I forgot ! You can use QGIS to load a map and add points or draw stuff, there's a lot of tutorials on the web.

Once you have a list of points, you will just have to load them (CSV/JSON), iterate over them and change the position of the red dot redraw the map, make a pause etc...

By the way, in the past, I have already worked on a code that generates N points for a path that have less than N points (e.g. a path defined using 30 points by we want to have the same path but with 1000 points. It uses scalar products and wasn't easy to code), so if someone needs it, I will make a demo and share it, I have used it backthen to color a path with data (color map).

**Comment by AmonRaNet** [comment]
1. Draw curve. For this you can create your custom Polyline. To make your curve smooth you can consider this article: https://www.toptal.com/c-plus-plus/rounded-corners-bezier-curves-qpainter . I would also recommend to check example from @embeddedmz 
2. Draw circle. You can use existing example in demo. Also you will need to add method or property to control position of circle (will be needed for animation control): https://github.com/AmonRaNet/QGeoView/blob/master/demo/samples/ellipse.cpp
3. Moving circle along curve. With QPainterPath you can get list of points along curve.
4. Animation: here is several solutions, probably easiest is based on QAnimation. You can simple iterate over values from 0.0 to 1.0, where value is percentage from start to end along the line.

Most closest to your case: 
https://github.com/AmonRaNet/QGeoView/blob/master/demo/samples/utilities.cpp
https://github.com/AmonRaNet/QGeoView/blob/master/demo/samples/waveanimation.cpp

It is not one-to-one to your case, but very close to it. It is demo with animated "QQeoView" text on map.

**Comment by wangdemon** [comment]
Thank you very much
