### ISSUE TITLE
Problem removing QGVDrawItem with childrens from QGVMap

### ISSUE THREAD

**Issue by JaiPasdeBol** [AmonRaNet/QGeoView#28]
Hi!
Still using in a very simple way your library!

But I have a new problem, I create a new type of QGVDrawItem, named entity, I add to those entity some SubEntities (by addItem()) that are also inheritate from QGVDrawItem. And I add my first entity to my QGVMap, by addItem(). Until here, no problem everything is working correctly.
But when I want to remove this entity by using QGVMap::removeItem(). The thread is going out of the removeItem() function but the application stop working an instant after. The call stack shows that some function of QGraphicsScene were called but failed ending sometimes with the method *QGraphicsItem::topLevelItem() const or with the method just uppon, QUndoView. I am aware that can be a pure virtual function problem but I have no function called in a specific destructor. By the way Entity and SubEntity have no specific destructor implemented.
If you have an idea or an exemple where you remove a QGVDrawItem containing few childrens it would be perfect.!

Thanks!

**Comment by JaiPasdeBol** [comment]
Hi!
I think I found the problem with [https://bugreports.qt.io/browse/QTBUG-18021](url) I didn't call resetBoundary() before I update the bounding rect so I guess I am ok now. I will keep you informed if the crash comes back

Thanks.

**Comment by AmonRaNet** [comment]
Thanks for sharing! Yes resetBoundary is mandatory prior to actual bounding rect update. 
It is interesting that I did same mistake myself in past, but have not made many accent on it. Problem is that is not so often when bounding rect need to be explicitly changed...
I plan to create kind of "HowTo" and there I will mention this issue!
