### ISSUE TITLE
Static library

### ISSUE THREAD

**Issue by OgreTransporter** [AmonRaNet/QGeoView#30]
I would include an additional query in `lib/include/QGeoView/QGVGlobal.h#L27`:

```
#ifndef QGV_LIB_DECL
#if defined(QGV_EXPORT)
#define QGV_LIB_DECL Q_DECL_EXPORT
#else
#define QGV_LIB_DECL Q_DECL_IMPORT
#endif
#endif
```

This enables the building of a static library.

**Comment by AmonRaNet** [comment]
Thanks! 
Yes is makes sense. Can you open PR for it?

**Comment by AmonRaNet** [comment]
Fixed
