### ISSUE TITLE
build error QGeoView

### ISSUE THREAD

**Issue by andrey-vanin** [AmonRaNet/QGeoView#47]
Здравствуйте!  Заинтересовался библиотекой QGeoView, хотел попробовать использовать в своем проекте, но при сборке проекта возникают ошибки. Не находятся какие-то функции. Не подскажите, что не хватает и как все же собрать библиотеку?
![build_error](https://github.com/AmonRaNet/QGeoView/assets/76805529/2428b09d-c7e3-4749-a764-84f5dbd10fb2)

**Comment by AmonRaNet** [comment]
Hey! Better on English to make it usable also for others.

I don't see anything suspicious. I have not build for long time for Windows, but should be fine. 

Can you try with relative paths, like
`qmake ../QGeoView-master`

Weird that it decides to do nothing for lib folder, but in same time basic.pro executed. Build folder is clear?

**Comment by andrey-vanin** [comment]
Hello! Thanks for the answer!When I tried to build, the build folder was completely empty. I downloaded the folder "QGeoView-1.0.4" somewhere and was able to run the example. Now, using the example, I’m implementing QGeoView into my application.  Is it possible to use a scanned map as a layer?  Thank you again!  Andrey 26.03.2024, 20:23, "AmonRaNet" ***@***.***>: Hey! Better on English to make it usable also for others.I don't see anything suspicious. I have not build for long time for Windows, but should be fine.Can you try with relative paths, likeqmake ../QGeoView-masterWeird that it decides to do nothing for lib folder, but in same time basic.pro executed. Build folder is clear?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by AmonRaNet** [comment]
Good! 
Custom raster is not directly related to topic of issue, therefore I will close issue.

Custom background layers are possible, but with effort. Generally QGV supports XYZ maps: online or offline. If you have such source - it will work with small effort.
As alternative you can use extra tools (like MapServer - https://mapserver.org/output/tile_mode.html) which can act as XYZ server for raw data.
